<?php
// generate_admin_sql.php
// Usage: php generate_admin_sql.php
// It will output a full SQL script: contents of sql/seed_data.sql plus an INSERT for admin with a secure password hash.

$seedPath = __DIR__ . '/sql/seed_data.sql';
if (!file_exists($seedPath)) {
    echo "ERROR: seed_data.sql not found at $seedPath\n";
    exit(1);
}

// --- CONFIGURE ADMIN CREDENTIALS BELOW ---
$adminEmail = 'admin@example.com';
$adminFirst = 'Admin';
$adminLast = 'User';
$adminPhone = '+84000000000';
$adminPassword = '123456'; // <= change if needed
// ----------------------------------------

$hash = password_hash($adminPassword, PASSWORD_DEFAULT);
$seed = file_get_contents($seedPath);

// Build admin insert SQL
$adminSql = "\n-- Admin user (generated by generate_admin_sql.php)\n";
$adminSql .= "INSERT INTO `Users` (`email`, `password_hash`, `first_name`, `last_name`, `phone`) VALUES ('" . addslashes($adminEmail) . "', '" . addslashes($hash) . "', '" . addslashes($adminFirst) . "', '" . addslashes($adminLast) . "', '" . addslashes($adminPhone) . "');\n";

// Output merged SQL
echo $seed . "\n" . $adminSql;

// Feedback
fwrite(STDERR, "Generated admin for $adminEmail with provided password.\n");
fwrite(STDERR, "To import: php generate_admin_sql.php > full_seed.sql && mysql -u root -p < full_seed.sql\n");
?>